name = "handles"
version = "1.0.0"

description = "Handles is a templating language written in pure Gleam. Heavily inspired by Mustache and Handlebars.js"
licences = ["MIT"]
repository = { type = "github", user = "olian04", repo = "gleam_handles" }


[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
